services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    entrypoint: ["/app/api/run.sh"]

  ui:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/dist
      - ./front/package.json:/app/package.json
      - ./front/yarn.lock:/app/yarn.lock
    command: ["yarn", "dev"]
